### ISSUE TITLE
Rocket speed control

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#1]
Add speed feature to the project

PLUS

* TDD/Tests

![image](https://user-images.githubusercontent.com/13206817/94974635-86c4d300-04e5-11eb-839d-cb2237eb5936.png)

![image](https://user-images.githubusercontent.com/13206817/94974843-2b471500-04e6-11eb-83ef-c776476a5db6.png)

**Comment by mothinx** [comment]
Hi ! Would like to work on this. Can you assign me please?

**Comment by mothinx** [comment]
@DanielVip3 already do speed control with https://github.com/pyymenta/spacecraft-cli/issues/3 .
Can you close this issue please ?

**Comment by pyymenta** [comment]
@mothinx If you want, you can be responsible for this issue and @DanielVip3 could adapt his solution according your work in this one. What do you think?

**Comment by DanielVip3** [comment]
Uhm, sorry! I already did the speed control too. Maybe I should have seen this before 😓

**Comment by pyymenta** [comment]
No problem guys, I'll close this when #17 is merged @DanielVip3 @mothinx
