### ISSUE TITLE
Use the json events to create the CLI events messages

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#19]
We have now a [file](https://github.com/pyymenta/spacecraft-cli/blob/master/src/events_messages.json) with the messages to use in our application, we need now to use it in your CLI

**Comment by CodeMartian** [comment]
Would I be able to take this on?

**Comment by pyymenta** [comment]
Go ahead @CodeMartian :+1: :+1: :+1:

**Comment by pyymenta** [comment]
Done!
