### ISSUE TITLE
Rocket move control

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#2]
Implement rocket movements

PLUS

* TDD/Tests

![image](https://user-images.githubusercontent.com/13206817/94974888-59c4f000-04e6-11eb-93e4-f2193080cb03.png)

![image](https://user-images.githubusercontent.com/13206817/94974923-782aeb80-04e6-11eb-80b1-4e04009fc557.png)

**Comment by null-sys** [comment]
Can i Work on this?

**Comment by pyymenta** [comment]
@null-sys It's yours! 🤘🤘
