### ISSUE TITLE
Add lint

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#22]
Add ESLint support to the project

Links that maybe can help:

https://eslint.org/
https://khalilstemmler.com/blogs/typescript/eslint-for-typescript/

**Comment by MounicaChanda0809** [comment]
Working on it

**Comment by pyymenta** [comment]
@MounicaChanda0809 Thanks for your interesting! Go ahead! 🚀🚀

**Comment by MounicaChanda0809** [comment]
> @MounicaChanda0809 Thanks for your interesting! Go ahead! 🚀🚀

Created PR. Please take a look when you have time :)

**Comment by pyymenta** [comment]
@MounicaChanda0809 Very nice! I'll review it soon! Thank you 😍😍

**Comment by pyymenta** [comment]
Resolved in #23
