### ISSUE TITLE
Draw a rocket on CLI initialization

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#24]
Draw a rocket 🚀 with characters on CLI init

Example:

![image](https://user-images.githubusercontent.com/13206817/95003782-3b7bf480-05b9-11eb-82ab-0f2e579584d8.png)

**Comment by yigitcukuren** [comment]
Hey, I have just tried something. Please see #32.

**Comment by pyymenta** [comment]
Fixed in #32 

Thank you @yigitcukuren !
