### ISSUE TITLE
Add collaborators section in our README

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#28]
Add an awesome collaborators sections at the end of our README file

Link that can help:

https://contributors-img.web.app/preview?repo=pyymenta%2Fspacecraft-cli

**Comment by EhrenfeldN** [comment]
@pyymenta i work on

**Comment by AlenST** [comment]
Implementing a manual version of the collaborator's section is a tedious task. There's a GitHub application that will help with automating this process.

Here's a link to the same:
https://allcontributors.org/docs/en/bot/installation

**Comment by hambali999** [comment]
Hi can you assign me to this task? this is my first5 hacktoberfest!!

**Comment by TheBrown** [comment]
Hi, I want to contribute the README.md

**Comment by pyymenta** [comment]
Anyone can find a way create the collaborators list automatically

**Comment by pyymenta** [comment]
Done in #34
