### ISSUE TITLE
Add commands using the keyboard A W S D

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#3]
Add the I/O commands to the CLI!

Something like this:

![Peek 2020-10-02 19-17](https://user-images.githubusercontent.com/13206817/94974145-08b3fc80-04e4-11eb-8d61-2b8158929d1b.gif)

**Comment by DanielVip3** [comment]
I'd like to contrib to this one (along with #2 and #1 which go together).
This project seems funny!

If I can, I'll create a class which is the base class for the CLI and another class which will take commands and communicate with the base class and change movement and speed values.

**Comment by pyymenta** [comment]
@DanielVip3 Seems great! You can work on It! I'll assign you in this issue!
