### ISSUE TITLE
Publish the package on npm

### ISSUE THREAD

**Issue by sudiptog81** [pyymenta/spacecraft-cli#44]
This will enable the users to install the CLI globally using `npm i-g spacecraft-cli` or by executing `npx spacecraft-cli`.

**Comment by pyymenta** [comment]
Thank you for your feedback @sudiptog81 

I'll work on it soon!

**Comment by pyymenta** [comment]
Done! We can use now with:

```sh
npm i -g spacecraft-app-cli
```

or

You can run directly with `npx`

```sh
npx spacecraft-app-cli
```

**Comment by pyymenta** [comment]
I'll close it now! Mission Accomplished! Thanks for your suggestion @sudiptog81
