### ISSUE TITLE
Add help command to the CLI

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#52]
Add help command with the instructions about how to use our CLI

**Comment by ish-u** [comment]
Hello,
I am new to Open Source.
I am trying this issue.

**Comment by pyymenta** [comment]
Of course @ish-u !! It's yours 👏👏

**Comment by sudiptog81** [comment]
#64 was made just in case merge resolution fails. I will close #64 in case #60 succeeds.
