### ISSUE TITLE
Add Jest Coverage Collector

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#54]
Add Jest Coverage Collector to the codebase

Links that might help:

https://jestjs.io/docs/en/cli#--collectcoveragefromglob
https://jestjs.io/docs/en/configuration#collectcoverage-boolean

**Comment by sudiptog81** [comment]
Can I work on this?

**Comment by pyymenta** [comment]
It's yours @sudiptog81
