### ISSUE TITLE
Configure eslint to ignore unnecessary folder

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#55]
We need to configure ESLint to ignore `dist` folder. Because this folders contains only transpiled code, and it shouldn't be linted.

**Comment by michalStarski** [comment]
Hey, can I take this issue?

**Comment by guilhermeorcezi** [comment]
Can I do this?

**Comment by pyymenta** [comment]
Hello @guilhermeorcezi, go ahead man, It's yours!
