### ISSUE TITLE
Prevent invalid input on keyboard inputs

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#7]
Validate when command is invalid, display a message like:

![image](https://user-images.githubusercontent.com/13206817/94974238-4d3f9800-04e4-11eb-83e3-432f58410441.png)

**Comment by krisstee** [comment]
Does this still need to be worked on? I can try working on this, if you'd like to assign to me.

**Comment by pyymenta** [comment]
@krisstee Yes, you can work on it, I'll assign to you!
