### ISSUE TITLE
Add events messages

### ISSUE THREAD

**Issue by pyymenta** [pyymenta/spacecraft-cli#8]
![image](https://user-images.githubusercontent.com/13206817/94974789-fcc93a00-04e5-11eb-8021-e415ca67f716.png)

**Comment by danielskjo** [comment]
Hi I would like to work on this

**Comment by pyymenta** [comment]
Great! I'll assign to you! :smiley:

**Comment by danielskjo** [comment]
What file do you want the events on? Sorry, I'm new to github

**Comment by pyymenta** [comment]
You can put a JSON file in the src folder, for example ;)

**Comment by danielskjo** [comment]
I can't do this without the commands being created though correct? Or maybe its bc im noob :/

**Comment by pyymenta** [comment]
Don't worry, the commands is not exists yet, but it's possible to create a list of messages or create a class with some `consts` with the messages to be use later, or something like that :smiley:

**Comment by pyymenta** [comment]
Fixed!
